### ISSUE TITLE
README recipe has stopped working after recent firmware update from lenovo

### ISSUE THREAD

**Issue by phaoost** [abrasive/xmm7360#11]
Hello,

I've got update from lenovo https://support.lenovo.com/nl/en/downloads/ds540197
After that `at+cfun=15` has stopped working (ttyACM0 disappears for some seconds after issued command). Then it returns back with `at+cfun?` with 4,0 default setting.
I have issued `at@nvm:fix_cat_fcclock.fcclock_mode=0` command and `AT+GTUSBMODE?` shows 7

**Comment by phaoost** [comment]
at@store_nvm(fix_cat_fcclock) fixed this

**Comment by Gottox** [comment]
This behavior should be documented.
