### ISSUE TITLE
What are the problems with this "fix"

### ISSUE THREAD

**Issue by nlincke** [abrasive/xmm7360#13]
Hi, 

this might be the wrong channel for this question but i am planning on buying a X1C7 with WAN and i read that this "fix" is quite promising…

I am curious what potential problems that could occur. I read that i could brick my new laptop? Is that right? Why and how? Is it likely?
Thanks in advanced!

Cheers!

**Comment by abrasive** [comment]
It won't brick anything. It also might not work!
