### ISSUE TITLE
Modem disappears from PCI, doesn't appear as USB device on Lenovo T495

### ISSUE THREAD

**Issue by niloc132** [abrasive/xmm7360#24]
Testing on a new T495, I get the expected output, as I understand it:
```
Found XMM7360 modem at 0000:04:00.0 (\_SB_.PCI0.GPP4.L850)
Parent port is at 0000:00:01.5
Disabling PCIe link...
OK!
```
But after this point, while the entry in `lspci -k` is gone, nothing is added to `lsusb -v -t` that I recognize, and no new `/dev/tty*` entry like the expected `/dev/ttyACM0`

`lspci -k` output for this modem before running the command:
```
04:00.0 Wireless controller [0d40]: Intel Corporation XMM7360 LTE Advanced Modem (rev 01)
	Subsystem: Intel Corporation XMM7360 LTE Advanced Modem
```
Full `lsusb -t -v` output, in case I missed it:
```
$ lsusb -t -v
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 1: Dev 2, If 1, Class=Wireless, Driver=btusb, 12M
        ID 8087:0025 Intel Corp. 
    |__ Port 1: Dev 2, If 0, Class=Wireless, Driver=btusb, 12M
        ID 8087:0025 Intel Corp. 
    |__ Port 2: Dev 3, If 0, Class=Hub, Driver=hub/4p, 480M
        ID 05e3:0610 Genesys Logic, Inc. 4-port hub
        |__ Port 1: Dev 4, If 0, Class=Video, Driver=uvcvideo, 480M
            ID 5986:2113 Acer, Inc 
        |__ Port 1: Dev 4, If 1, Class=Video, Driver=uvcvideo, 480M
            ID 5986:2113 Acer, Inc 
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/1p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
```

The modem is functional in Windows 10.

**Comment by enzingerm** [comment]
Exactly the same is happening with my T495. I wonder if somehow the USB Pins are not accessible from the OS, but why and how?

**Comment by enzingerm** [comment]
I also tried to tape off the PCIe Pins and plug the Modem back in (as suggested in this thread: https://forums.lenovo.com/t5/Other-Linux-Discussions/Linux-status-of-Fibocom-L850-Gl/td-p/4082434). Interestingly, this did not trigger any BIOS Whitelist errors but neither did the USB device appear.

**Comment by abrasive** [comment]
Incompatibility noted in README.

Closing this ticket in favour of [the PCI driver effort](https://github.com/xmm7360/xmm7360-pci)
