### ISSUE TITLE
How to build on kernel 5

### ISSUE THREAD

**Issue by kopax** [abrasive/xmm7360#25]
Hi and merry xmas! 
In order to get the microphone and the finger print reader, I needed to upgrade the kernel  of my Debian Buster to kernel v5 or over.

After installing the new kernel, I noticed that my `mmbim` device was not showing up anymore in `modem-manager-gui`.

I wanted to rebuild [the xmm7360 driver](https://github.com/juhovh/xmm7360_usb), but the `make` command now fail:

```bash

dka@dka:[~/workspace/github.com/juhovh/xmm7360_usb (master)]: make
make -C /lib/modules/5.3.0-0.bpo.2-amd64/build M=/home/dka/workspace/github.com/juhovh/xmm7360_usb modules
make[1]: *** /lib/modules/5.3.0-0.bpo.2-amd64/build: No such file or directory. Stop.
make: *** [Makefile:8: default] Error 2
```

It seems that `/lib/modules/4.19.0-6-amd64/build` is providing tooling from `linux-kbuild-4.19`:

```bash
dka@dka:[/lib/modules/4.19.0-6-amd64/build]: ll
total 1552
lrwxrwxrwx 1 root root 33 Sep 20 12:51 tools -> ../../lib/linux-kbuild-4.19/tools
lrwxrwxrwx 1 root root 35 Sep 20 12:51 scripts -> ../../lib/linux-kbuild-4.19/scripts
drwxr-xr-x 3 root root 4096 Oct 29 19:36 arch
drwxr-xr-x 4 root root 4096 Oct 29 19:36 include
lrwxrwxrwx 1 root root 42 Oct 30 18:25 Kconfig -> /lib/modules/4.19.0-6-amd64/build/Makefile
-rw-r--r-- 1 root root 1353400 Nov 11 01:30 Module.symvers
-rw-r--r-- 1 root root 306 Nov 11 01:30 Makefile
-rw-r--r-- 1 root root 243 Nov 11 01:30 .kernelvariables
-rw-r--r-- 1 root root 206361 Nov 11 01:30 .config
drwxr-xr-x 4 root root 4096 Nov 26 01:20 .

```

Those tool are not within `/lib/modules/5.3.0-0.bpo.2-amd64/build` which is not created directory.

Because the kernel v4.19 had some symlink to `../../lib/linux-kbuild-4.19/tools`, I figure out that I needed to install `linux-kbuild-5.3`.

After installing it, I still do not have the symlink. Why? I am not able to build the driver and use the Fibocom device.

How can I fix the build environment in the new kernel? Or how can I restore the driver?  

thanks for the help and best!

**Comment by abrasive** [comment]
Wrong repo :-)
