### ISSUE TITLE
Offer of help in reverse-engineering the PCI driver

### ISSUE THREAD

**Issue by thotypous** [abrasive/xmm7360#26]
Dear @abrasive,

Would you please share your work reverse-engineering the PCI driver so that I can start from where you stopped?

Any test code you wrote or IDA Pro idb/i64 files would be really appreciated. Is it already published anywhere in GitHub?

In case you don't want to publish stuff, you can reach me to share privately by email (please see my GitHub profile) or through Telegram or Keybase (same nickname as my GitHub account).

Thank you!

**Comment by abrasive** [comment]
Sent you an email and pushed an xmm7360/reversing repo

**Comment by thotypous** [comment]
Thank you very much. I will buy a T495 and ask the Fibocom to be included. I should be able to work on RE by the end of January.
