### ISSUE TITLE
Ues setpci, which is not available with a lockdown kernel

### ISSUE THREAD

**Issue by eriktews** [abrasive/xmm7360#27]
The current script uses setpci, which doesn't work with a default Debian setup using Secure Boot. The reason for this is that the kernel uses the lockdown feature, which is automatically enabled on a secure boot system. In lockdown mode, setpci cannot be used.

However I don't see a good way how to fix this. The only thing that is allowed is loading signed kernel modules, so when you could re-implement what setpci does in a custom kernel module, then you could circumvent this restriction and use the script on a system with a kernel lockdown mode.

**Comment by abrasive** [comment]
https://github.com/juhovh/xmm7360_usb

**Comment by eriktews** [comment]
Thanks, the kernel module looks pretty clean. The only exception is maybe this line where you might need some more error checking: https://github.com/juhovh/xmm7360_usb/blob/master/xmm7360_usb.c#L43

**Comment by abrasive** [comment]
Good catch! I'm not the author of that one, but I'm sure they'd appreciate a patch :-)
