### ISSUE TITLE
PCIe link fails with operation not permitted

### ISSUE THREAD

**Issue by cstranex** [abrasive/xmm7360#9]
After running xmm2usb as root on a fresh install on Ubuntu 19.10 (Lenovo T480s):

```
Disabling PCIe link...
pcilib: sysfs_write: write failed: Operation not permitted
```

Any ideas?

**Comment by abrasive** [comment]
selinux? AppArmor? Does the sysfs config file actually exist? (I don't think it's a configurable kernel option but could be wrong)

**Comment by cstranex** [comment]
doh.. fails because the kernel is in lockdown

For anyone else having issues:
```
sysctl -w kernel.sysrq=1
echo x  > /proc/sysrq-trigger
```

will lift the lockdown
